In [60]:
import torch
import numpy as np

### torch.empty returns tensor with garbage/uninitialsed data

In [2]:
x=torch.empty(1)

In [3]:
x

tensor([4.6425e+30])

In [10]:
x=torch.empty(3,2,4)
x

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0102e-38, 7.7052e+31, 7.2148e+22]],

        [[2.5226e-18, 2.5930e-09, 1.0072e-11, 7.7202e-10],
         [6.7140e-07, 4.2111e-11, 4.2886e-08, 2.9572e-18]],

        [[6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]]])

torch.zeros for o tensor,rand for 0-1 ,rand1 for normally distributed

In [14]:
x=torch.zeros(2,2)
y=torch.rand(3,4)
print(x)
print(y)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4791, 0.1945, 0.1979, 0.3157],
        [0.2288, 0.1607, 0.6693, 0.2472],
        [0.3262, 0.8738, 0.5718, 0.8442]])


In [25]:
z=torch.ones(4,5,dtype=torch.int)
z

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [26]:
print(z.type())
print(z.size())

torch.IntTensor
torch.Size([4, 5])


### LIST TO TENSOR

In [27]:
l=[1,2,3]
x=torch.tensor(l)
print(x)

tensor([1, 2, 3])


### arithmetic

In [29]:
z=torch.randn(2,3)
y=torch.randn(2,3)
#both below used for addition(element wise)
x1=z+y
x2=torch.add(z,y)
print(x1)
print(x2)

tensor([[ 1.1776, -0.3009,  0.3627],
        [-0.5445, -0.0515,  0.0921]])
tensor([[ 1.1776, -0.3009,  0.3627],
        [-0.5445, -0.0515,  0.0921]])


In [35]:
z.add_(y) #z=z-y whenever _ then it means inplace operation.
print(z)

tensor([[ 0.7893, -0.6224,  0.7594],
        [-0.2857, -0.0273, -1.0312]])


In [39]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.9883, 0.8575],
        [0.9473, 0.0138]])
tensor([[0.2629, 0.0221],
        [0.5558, 0.6733]])


In [41]:
print(x*y)##element wise
#all these are inplace element wise operations
x.add_(y)
x.mul_(y)
x.div_(y)
print(x)

tensor([[0.2598, 0.0190],
        [0.5265, 0.0093]])
tensor([[1.2512, 0.8796],
        [1.5030, 0.6871]])


In [45]:
x=torch.rand(5,4)
print(x)

tensor([[0.6317, 0.3196, 0.2519, 0.1510],
        [0.8509, 0.2822, 0.0105, 0.8150],
        [0.6411, 0.0696, 0.4995, 0.3775],
        [0.9689, 0.2310, 0.9045, 0.9568],
        [0.9566, 0.5730, 0.5265, 0.0364]])


### slicing basics 

In [53]:
print(x[:,2])
print(x[3,1:])
print(x[2:,1:3])
print(x[1][1])
print(x[1][1].item()) # to get value , use only if one item in tensor

tensor([0.2519, 0.0105, 0.4995, 0.9045, 0.5265])
tensor([0.2310, 0.9045, 0.9568])
tensor([[0.0696, 0.4995],
        [0.2310, 0.9045],
        [0.5730, 0.5265]])
tensor(0.2822)
0.2821626663208008


### RESHAPING

In [56]:
x = torch.rand(4,4)
#.view for replacing
a = x.view(1,16)
b = x.view(2,8)
c = x.view(8,-1) #-11 automatically filled with correct val
print(c.size())

torch.Size([8, 2])


### Numpy and tensor

In [77]:
#TORCH TO NUMPY
a=torch.rand(4)
b=a.numpy()
print(a)
print(b)
a.add_(1)
print()
print('after adding')
print()
print(a)
print(b)

#Hence b,a share same memory so updating one will update array too.

b+=3
print(a)
print(b)


#NOTE -> b=b+3 will create b with val b+3 in another memory location. SO now they will be independednt. but b+=3 updates the same memoery

tensor([0.1022, 0.9042, 0.9470, 0.7682])
[0.10221785 0.90415925 0.947048   0.7682152 ]

after adding

tensor([1.1022, 1.9042, 1.9470, 1.7682])
[1.1022179 1.9041593 1.947048  1.7682152]
tensor([4.1022, 4.9042, 4.9470, 4.7682])
[4.1022177 4.9041595 4.947048  4.768215 ]


In [72]:
#NUMPY TO TORCH
a=np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

a+=1
print(a)
print(b)

b.add_(2)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


### CPU GPU SWITCHING

In [78]:
if(torch.cuda.is_available()):
    device = torch.device('cuda')
    x = torch.ones(5,device=device) #in GPU
    y = torch.ones(5) # in CPU
    y = y.to(device) #in GPU now
    z = x+y #this happens in GPU
    z.numpy()# this will give error as NUMPY cannot handle GPU tensors,only CPU
    #hence do this
    z.to('cpu')#now back in cpu
    z.numpy()#this will work now

False